const mongoose = require("mongoose");

const measurementSchema = new mongoose.Schema(
    {
        patientId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Patient",
            required: true
        },

        // Automatically generated by the backend:
        // Visit 1, Visit 2, Visit 3, ...
        visitNumber: {
            type: Number,
            required: true
        },

        date: {
            type: Date,
            required: true
        },

        // eGFR calculated by the ML/Flask service
        calculatedEGFR: {
            type: Number,
            required: true
        },

        // Final clinician-confirmed eGFR
        // This is the value used for patient history
        // and progression analysis.
        finalEGFR: {
            type: Number,
            required: true
        },

        serumCreatinine: {
            type: Number,
            required: true
        },

        UACR: {
            type: Number,
            required: true
        },

        systolicBP: {
            type: Number,
            required: true
        },

        diastolicBP: {
            type: Number,
            required: true
        },

        diabetes: {
            type: Number,
            required: true
        },

        ckdPrediction: {
            type: Number
        },

        ckdProbability: {
            type: Number
        }
    },
    {
        timestamps: true
    }
);


// One visit number per patient
measurementSchema.index(
    {
        patientId: 1,
        visitNumber: 1
    },
    {
        unique: true
    }
);


module.exports = mongoose.model(
    "Measurement",
    measurementSchema
);
